
GET http://localhost:3000/users
###
GET http://localhost:3000/user/bilge.m01@htlwienwest.at
###
POST http://localhost:3000/user/createNewOne
content-Type: application/json

{
    "email": "wolfsberger.r03@htlwienwest.at",
    "firstname": "Raphael",
    "lastname": "Wolfsberger",
    "password": "test123"
}
###
GET http://localhost:3000/getCompetitions/0
###
POST http://localhost:3000/createNewCompetition
content-Type: application/json

{
    "title": "CRUD-POST-Competition",
    "starting_money": 20000,
    "end_date": "2022-12-1",
    "user_id": "8"
}
###
GET http://localhost:3000/competitions/0

###
GET http://localhost:3000/users/0
###
POST http://localhost:3000/user/buyStocks
content-Type: application/json

{
    "isin": "US5949181045",
    "buy_price": 298.76,
    "count": 5,
    "competition_id": 0,
    "buy_date": "2022-01-12"
}
###
GET http://localhost:3000/user/competitions
