GET http://localhost:3000/users
###
GET http://localhost:3000/user/bilge.m01@htlwienwest.at
###
POST http://localhost:3000/user/createNewOne
content-Type: application/json

{
    "email": "woalfsberger.r03@htlwienwest.at",
    "firstname": "Raphael",
    "lastname": "Wolfsberger",
    "password": "test123"
}
###
GET http://localhost:3000/users/competitions